/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import java.io.File;
import com.brand4impact.client.model.PlatformCompany;
import com.brand4impact.client.model.PlatformCompanyCreate;
import com.brand4impact.client.model.PlatformCompanyCreateAdmin;
import com.brand4impact.client.model.PlatformCompanyCreateLegal;
import com.brand4impact.client.model.PlatformCompanyUpdate;
import com.brand4impact.client.model.PlatformCompanyUpdateLegal;
import com.brand4impact.client.model.PlatformCompanyUpdateTopic;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyApi
 */
@Ignore
public class CompanyApiTest {

    private final CompanyApi api = new CompanyApi();

    
    /**
     * Create a new Company
     *
     * Register a new company allows you to start to have visibility that your deserves, being visible to brand4impact users and opting to donate among a bunch of projects
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCompanyTest() throws ApiException {
        PlatformCompanyCreate company = null;
        PlatformCompanyCreateLegal legal = null;
        PlatformCompanyCreateAdmin admin = null;
                PlatformCompany response = api.createCompany(company, legal, admin);
        // TODO: test validations
    }
    
    /**
     * Get your Company
     *
     * This method returns the Company inside your tenant (theres no need to know the Company token)  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyTest() throws ApiException {
                PlatformCompany response = api.getCompany();
        // TODO: test validations
    }
    
    /**
     * Update Company data
     *
     * This method updates any data for the Company  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCompanyTest() throws ApiException {
        PlatformCompanyUpdate company = null;
        File logo = null;
                PlatformCompany response = api.updateCompany(company, logo);
        // TODO: test validations
    }
    
    /**
     * Update legal Company info
     *
     * This method updates the legal info for your Company  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCompanyLegalTest() throws ApiException {
        PlatformCompanyUpdateLegal legal = null;
                PlatformCompany response = api.updateCompanyLegal(legal);
        // TODO: test validations
    }
    
    /**
     * Update selected topics for your Company
     *
     * This method updates to which topics they can donate the vouchers of their campaigns  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCompanyTopicTest() throws ApiException {
        PlatformCompanyUpdateTopic sdg = null;
                PlatformCompany response = api.updateCompanyTopic(sdg);
        // TODO: test validations
    }
    
}
