/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import java.io.File;
import com.brand4impact.client.model.PlatformNgo;
import com.brand4impact.client.model.PlatformNgoCreate;
import com.brand4impact.client.model.PlatformNgoCreateAdmin;
import com.brand4impact.client.model.PlatformNgoCreateLegal;
import com.brand4impact.client.model.PlatformNgoUpdate;
import com.brand4impact.client.model.PlatformNgoUpdateBank;
import com.brand4impact.client.model.PlatformNgoUpdateLegal;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NgoApi
 */
@Ignore
public class NgoApiTest {

    private final NgoApi api = new NgoApi();

    
    /**
     * Create a new NGO
     *
     * Register a new NGO allows you to have visibiliy that your NGO deserves, being visible to brand4impact users, and opting for their donations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createNgoTest() throws ApiException {
        PlatformNgoCreate ngo = null;
        PlatformNgoCreateLegal legal = null;
        PlatformNgoCreateAdmin admin = null;
                PlatformNgo response = api.createNgo(ngo, legal, admin);
        // TODO: test validations
    }
    
    /**
     * Get your NGO
     *
     * This method returns the NGO inside your tenant (theres no need to know the NGO token)  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNgoTest() throws ApiException {
                PlatformNgo response = api.getNgo();
        // TODO: test validations
    }
    
    /**
     * Update NGO data
     *
     * This method updates any data for the NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNgoTest() throws ApiException {
        PlatformNgoUpdate ngo = null;
        File logo = null;
                PlatformNgo response = api.updateNgo(ngo, logo);
        // TODO: test validations
    }
    
    /**
     * Update bank NGO info
     *
     * This method updates the bank info for your NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNgoBankTest() throws ApiException {
        PlatformNgoUpdateBank bank = null;
                PlatformNgo response = api.updateNgoBank(bank);
        // TODO: test validations
    }
    
    /**
     * Update legal NGO info
     *
     * This method updates the legal info for your NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNgoLegalTest() throws ApiException {
        PlatformNgoUpdateLegal legal = null;
                PlatformNgo response = api.updateNgoLegal(legal);
        // TODO: test validations
    }
    
    /**
     * Upload NGO files
     *
     * This method uploads documentation (files, images, ...) of a NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadNgoFilesTest() throws ApiException {
        File file = null;
                PlatformNgo response = api.uploadNgoFiles(file);
        // TODO: test validations
    }
    
}
