/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import java.io.File;
import com.brand4impact.client.model.PlatformProject;
import com.brand4impact.client.model.PlatformProjectCreate;
import com.brand4impact.client.model.PlatformProjectItemWrapper;
import com.brand4impact.client.model.PlatformProjectUpdate;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectApi
 */
@Ignore
public class ProjectApiTest {

    private final ProjectApi api = new ProjectApi();

    
    /**
     * Create a new project
     *
     * This method creates a new project within a NGO  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProjectTest() throws ApiException {
        PlatformProjectCreate project = null;
        File primaryImage = null;
        File secondaryImage = null;
                PlatformProject response = api.createProject(project, primaryImage, secondaryImage);
        // TODO: test validations
    }
    
    /**
     * Get a single project
     *
     * This method returns a specific project within your tenant  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectTest() throws ApiException {
        String token = null;
                PlatformProject response = api.getProject(token);
        // TODO: test validations
    }
    
    /**
     * Get a set of projects
     *
     * This method returns a set of projects within your tenant    [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)[![pagination](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/brackets.png &#39;pagination&#39;)](http://localhost:8080/backend/blog/home#pagination)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectsTest() throws ApiException {
        String descriptionLike = null;
        String country = null;
        String topicToken = null;
        Integer page = null;
        Integer size = null;
        String sort = null;
                PlatformProjectItemWrapper response = api.getProjects(descriptionLike, country, topicToken, page, size, sort);
        // TODO: test validations
    }
    
    /**
     * Switch project status
     *
     * This method switch the status of a specific project  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void switchProjectTest() throws ApiException {
        String token = null;
                PlatformProject response = api.switchProject(token);
        // TODO: test validations
    }
    
    /**
     * Update a project
     *
     * This method updates an existing project  [![security](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/shield-check.png &#39;security&#39;)](http://localhost:8080/backend/blog/home#seguridad)[![multi-tenant](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/users.png &#39;multi-tenant&#39;)](http://localhost:8080/backend/blog/home#multitenant)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProjectTest() throws ApiException {
        String token = null;
        PlatformProjectUpdate project = null;
        File primaryImage = null;
        File secondaryImage = null;
                PlatformProject response = api.updateProject(token, project, primaryImage, secondaryImage);
        // TODO: test validations
    }
    
}
