/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import com.brand4impact.client.model.PlatformSector;
import com.brand4impact.client.model.PlatformSectorItemWrapper;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SectorApi
 */
@Ignore
public class SectorApiTest {

    private final SectorApi api = new SectorApi();

    
    /**
     * Get a single sector
     *
     * This method returns a specific sector and represents principals industries  
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectorTest() throws ApiException {
        String token = null;
                PlatformSector response = api.getSector(token);
        // TODO: test validations
    }
    
    /**
     * Get a set of sectors
     *
     * This method returns all the sectors according the filters and represents principals industries    [![pagination](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/brackets.png &#39;pagination&#39;)](http://localhost:8080/backend/blog/home#pagination)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSectorsTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        String sort = null;
                PlatformSectorItemWrapper response = api.getSectors(page, size, sort);
        // TODO: test validations
    }
    
}
