/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import com.brand4impact.client.model.PlatformTopic;
import com.brand4impact.client.model.PlatformTopicItemWrapper;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TopicApi
 */
@Ignore
public class TopicApiTest {

    private final TopicApi api = new TopicApi();

    
    /**
     * Get a single topic
     *
     * This method returns a specific topic  A topic refers to the 17th SDG objectives [(United Nations)](https://sdgs.un.org/goals)  
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopicTest() throws ApiException {
        String token = null;
                PlatformTopic response = api.getTopic(token);
        // TODO: test validations
    }
    
    /**
     * Get a set of topics
     *
     * This method returns all the topics according the filters  A topic refers to the 17th SDG objectives [(United Nations)](https://sdgs.un.org/goals)    [![pagination](https://b4i.ams3.digitaloceanspaces.com/statics/swagger/brackets.png &#39;pagination&#39;)](http://localhost:8080/backend/blog/home#pagination)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopicsTest() throws ApiException {
        String titleLike = null;
        Integer page = null;
        Integer size = null;
        String sort = null;
                PlatformTopicItemWrapper response = api.getTopics(titleLike, page, size, sort);
        // TODO: test validations
    }
    
}
