/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.api;

import com.brand4impact.client.invoker.ApiException;
import com.brand4impact.client.model.PlatformCountry;
import com.brand4impact.client.model.PlatformCurrency;
import com.brand4impact.client.model.PlatformLanguage;
import com.brand4impact.client.model.PlatformRole;
import com.brand4impact.client.model.PlatformZone;
import com.brand4impact.client.model.RestError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UtilsApi
 */
@Ignore
public class UtilsApiTest {

    private final UtilsApi api = new UtilsApi();

    
    /**
     * Get countries
     *
     * This method returns all the countries available, you can indicate a locale to do the search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCountriesTest() throws ApiException {
        String language = null;
                List<PlatformCountry> response = api.getCountries(language);
        // TODO: test validations
    }
    
    /**
     * Get currencies
     *
     * This method returns all the currencies available, you can indicate a locale to do the search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrenciesTest() throws ApiException {
        String language = null;
                List<PlatformCurrency> response = api.getCurrencies(language);
        // TODO: test validations
    }
    
    /**
     * Get languages
     *
     * This method returns all the languages available, you can indicate a locale to do the search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLanguagesTest() throws ApiException {
        String language = null;
                List<PlatformLanguage> response = api.getLanguages(language);
        // TODO: test validations
    }
    
    /**
     * Get roles
     *
     * This method returns all the roles available, you can indicate a locale to do the search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRolesTest() throws ApiException {
                List<PlatformRole> response = api.getRoles();
        // TODO: test validations
    }
    
    /**
     * Get zones
     *
     * This method returns all the zones available, you can indicate a locale to do the search
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getZonesTest() throws ApiException {
        String language = null;
                List<PlatformZone> response = api.getZones(language);
        // TODO: test validations
    }
    
}
