/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.brand4impact.client.model.PlatformCompanyLegalAddress;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * PlatformCompanyLegal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-31T15:35:43.909+02:00[Europe/Paris]")
public class PlatformCompanyLegal {
  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_FIRSTNAME = "firstname";
  @SerializedName(SERIALIZED_NAME_FIRSTNAME)
  private String firstname;

  public static final String SERIALIZED_NAME_LASTNAME = "lastname";
  @SerializedName(SERIALIZED_NAME_LASTNAME)
  private String lastname;

  public static final String SERIALIZED_NAME_NID = "nid";
  @SerializedName(SERIALIZED_NAME_NID)
  private String nid;

  public static final String SERIALIZED_NAME_BRITHDAY = "brithday";
  @SerializedName(SERIALIZED_NAME_BRITHDAY)
  private OffsetDateTime brithday;

  public static final String SERIALIZED_NAME_NATIONALITY = "nationality";
  @SerializedName(SERIALIZED_NAME_NATIONALITY)
  private String nationality;

  public static final String SERIALIZED_NAME_RESIDENCE = "residence";
  @SerializedName(SERIALIZED_NAME_RESIDENCE)
  private String residence;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private PlatformCompanyLegalAddress address;


  public PlatformCompanyLegal token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public PlatformCompanyLegal firstname(String firstname) {
    
    this.firstname = firstname;
    return this;
  }

   /**
   * Get firstname
   * @return firstname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirstname() {
    return firstname;
  }


  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }


  public PlatformCompanyLegal lastname(String lastname) {
    
    this.lastname = lastname;
    return this;
  }

   /**
   * Get lastname
   * @return lastname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastname() {
    return lastname;
  }


  public void setLastname(String lastname) {
    this.lastname = lastname;
  }


  public PlatformCompanyLegal nid(String nid) {
    
    this.nid = nid;
    return this;
  }

   /**
   * Get nid
   * @return nid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNid() {
    return nid;
  }


  public void setNid(String nid) {
    this.nid = nid;
  }


  public PlatformCompanyLegal brithday(OffsetDateTime brithday) {
    
    this.brithday = brithday;
    return this;
  }

   /**
   * Get brithday
   * @return brithday
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getBrithday() {
    return brithday;
  }


  public void setBrithday(OffsetDateTime brithday) {
    this.brithday = brithday;
  }


  public PlatformCompanyLegal nationality(String nationality) {
    
    this.nationality = nationality;
    return this;
  }

   /**
   * Get nationality
   * @return nationality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNationality() {
    return nationality;
  }


  public void setNationality(String nationality) {
    this.nationality = nationality;
  }


  public PlatformCompanyLegal residence(String residence) {
    
    this.residence = residence;
    return this;
  }

   /**
   * Get residence
   * @return residence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getResidence() {
    return residence;
  }


  public void setResidence(String residence) {
    this.residence = residence;
  }


  public PlatformCompanyLegal email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public PlatformCompanyLegal address(PlatformCompanyLegalAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PlatformCompanyLegalAddress getAddress() {
    return address;
  }


  public void setAddress(PlatformCompanyLegalAddress address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformCompanyLegal platformCompanyLegal = (PlatformCompanyLegal) o;
    return Objects.equals(this.token, platformCompanyLegal.token) &&
        Objects.equals(this.firstname, platformCompanyLegal.firstname) &&
        Objects.equals(this.lastname, platformCompanyLegal.lastname) &&
        Objects.equals(this.nid, platformCompanyLegal.nid) &&
        Objects.equals(this.brithday, platformCompanyLegal.brithday) &&
        Objects.equals(this.nationality, platformCompanyLegal.nationality) &&
        Objects.equals(this.residence, platformCompanyLegal.residence) &&
        Objects.equals(this.email, platformCompanyLegal.email) &&
        Objects.equals(this.address, platformCompanyLegal.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, firstname, lastname, nid, brithday, nationality, residence, email, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformCompanyLegal {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    nid: ").append(toIndentedString(nid)).append("\n");
    sb.append("    brithday: ").append(toIndentedString(brithday)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    residence: ").append(toIndentedString(residence)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

