/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * PlatformProject
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-31T15:35:43.909+02:00[Europe/Paris]")
public class PlatformProject {
  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_STARTDATE = "startdate";
  @SerializedName(SERIALIZED_NAME_STARTDATE)
  private OffsetDateTime startdate;

  public static final String SERIALIZED_NAME_ENDDATE = "enddate";
  @SerializedName(SERIALIZED_NAME_ENDDATE)
  private OffsetDateTime enddate;

  public static final String SERIALIZED_NAME_PRIMARY_IMAGE_TOKEN = "primaryImageToken";
  @SerializedName(SERIALIZED_NAME_PRIMARY_IMAGE_TOKEN)
  private String primaryImageToken;

  public static final String SERIALIZED_NAME_SECONDARY_IMAGE_TOKEN = "secondaryImageToken";
  @SerializedName(SERIALIZED_NAME_SECONDARY_IMAGE_TOKEN)
  private String secondaryImageToken;

  public static final String SERIALIZED_NAME_VIDEO_URL = "videoUrl";
  @SerializedName(SERIALIZED_NAME_VIDEO_URL)
  private String videoUrl;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_BUDGET = "budget";
  @SerializedName(SERIALIZED_NAME_BUDGET)
  private Double budget;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;


  public PlatformProject token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public PlatformProject id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public PlatformProject title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public PlatformProject description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PlatformProject startdate(OffsetDateTime startdate) {
    
    this.startdate = startdate;
    return this;
  }

   /**
   * Get startdate
   * @return startdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartdate() {
    return startdate;
  }


  public void setStartdate(OffsetDateTime startdate) {
    this.startdate = startdate;
  }


  public PlatformProject enddate(OffsetDateTime enddate) {
    
    this.enddate = enddate;
    return this;
  }

   /**
   * Get enddate
   * @return enddate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getEnddate() {
    return enddate;
  }


  public void setEnddate(OffsetDateTime enddate) {
    this.enddate = enddate;
  }


  public PlatformProject primaryImageToken(String primaryImageToken) {
    
    this.primaryImageToken = primaryImageToken;
    return this;
  }

   /**
   * Get primaryImageToken
   * @return primaryImageToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrimaryImageToken() {
    return primaryImageToken;
  }


  public void setPrimaryImageToken(String primaryImageToken) {
    this.primaryImageToken = primaryImageToken;
  }


  public PlatformProject secondaryImageToken(String secondaryImageToken) {
    
    this.secondaryImageToken = secondaryImageToken;
    return this;
  }

   /**
   * Get secondaryImageToken
   * @return secondaryImageToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSecondaryImageToken() {
    return secondaryImageToken;
  }


  public void setSecondaryImageToken(String secondaryImageToken) {
    this.secondaryImageToken = secondaryImageToken;
  }


  public PlatformProject videoUrl(String videoUrl) {
    
    this.videoUrl = videoUrl;
    return this;
  }

   /**
   * Get videoUrl
   * @return videoUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVideoUrl() {
    return videoUrl;
  }


  public void setVideoUrl(String videoUrl) {
    this.videoUrl = videoUrl;
  }


  public PlatformProject status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public PlatformProject budget(Double budget) {
    
    this.budget = budget;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getBudget() {
    return budget;
  }


  public void setBudget(Double budget) {
    this.budget = budget;
  }


  public PlatformProject currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformProject platformProject = (PlatformProject) o;
    return Objects.equals(this.token, platformProject.token) &&
        Objects.equals(this.id, platformProject.id) &&
        Objects.equals(this.title, platformProject.title) &&
        Objects.equals(this.description, platformProject.description) &&
        Objects.equals(this.startdate, platformProject.startdate) &&
        Objects.equals(this.enddate, platformProject.enddate) &&
        Objects.equals(this.primaryImageToken, platformProject.primaryImageToken) &&
        Objects.equals(this.secondaryImageToken, platformProject.secondaryImageToken) &&
        Objects.equals(this.videoUrl, platformProject.videoUrl) &&
        Objects.equals(this.status, platformProject.status) &&
        Objects.equals(this.budget, platformProject.budget) &&
        Objects.equals(this.currency, platformProject.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, id, title, description, startdate, enddate, primaryImageToken, secondaryImageToken, videoUrl, status, budget, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformProject {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    startdate: ").append(toIndentedString(startdate)).append("\n");
    sb.append("    enddate: ").append(toIndentedString(enddate)).append("\n");
    sb.append("    primaryImageToken: ").append(toIndentedString(primaryImageToken)).append("\n");
    sb.append("    secondaryImageToken: ").append(toIndentedString(secondaryImageToken)).append("\n");
    sb.append("    videoUrl: ").append(toIndentedString(videoUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

