/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.brand4impact.client.model.PlatformInvoiceEntry;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * PlatformInvoice
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-31T15:35:43.909+02:00[Europe/Paris]")
public class PlatformInvoice {
  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NUMBER = "number";
  @SerializedName(SERIALIZED_NAME_NUMBER)
  private String number;

  public static final String SERIALIZED_NAME_STARTDATE = "startdate";
  @SerializedName(SERIALIZED_NAME_STARTDATE)
  private OffsetDateTime startdate;

  public static final String SERIALIZED_NAME_ENDDATE = "enddate";
  @SerializedName(SERIALIZED_NAME_ENDDATE)
  private OffsetDateTime enddate;

  public static final String SERIALIZED_NAME_ISSUEDATE = "issuedate";
  @SerializedName(SERIALIZED_NAME_ISSUEDATE)
  private OffsetDateTime issuedate;

  public static final String SERIALIZED_NAME_CLIENT_NAME = "clientName";
  @SerializedName(SERIALIZED_NAME_CLIENT_NAME)
  private String clientName;

  public static final String SERIALIZED_NAME_CLIENT_VAT = "clientVat";
  @SerializedName(SERIALIZED_NAME_CLIENT_VAT)
  private String clientVat;

  public static final String SERIALIZED_NAME_CLIENT_ADDRESS = "clientAddress";
  @SerializedName(SERIALIZED_NAME_CLIENT_ADDRESS)
  private String clientAddress;

  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private Map<String, List<PlatformInvoiceEntry>> entries = null;


  public PlatformInvoice token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public PlatformInvoice id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public PlatformInvoice number(String number) {
    
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNumber() {
    return number;
  }


  public void setNumber(String number) {
    this.number = number;
  }


  public PlatformInvoice startdate(OffsetDateTime startdate) {
    
    this.startdate = startdate;
    return this;
  }

   /**
   * Get startdate
   * @return startdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartdate() {
    return startdate;
  }


  public void setStartdate(OffsetDateTime startdate) {
    this.startdate = startdate;
  }


  public PlatformInvoice enddate(OffsetDateTime enddate) {
    
    this.enddate = enddate;
    return this;
  }

   /**
   * Get enddate
   * @return enddate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getEnddate() {
    return enddate;
  }


  public void setEnddate(OffsetDateTime enddate) {
    this.enddate = enddate;
  }


  public PlatformInvoice issuedate(OffsetDateTime issuedate) {
    
    this.issuedate = issuedate;
    return this;
  }

   /**
   * Get issuedate
   * @return issuedate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getIssuedate() {
    return issuedate;
  }


  public void setIssuedate(OffsetDateTime issuedate) {
    this.issuedate = issuedate;
  }


  public PlatformInvoice clientName(String clientName) {
    
    this.clientName = clientName;
    return this;
  }

   /**
   * Get clientName
   * @return clientName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientName() {
    return clientName;
  }


  public void setClientName(String clientName) {
    this.clientName = clientName;
  }


  public PlatformInvoice clientVat(String clientVat) {
    
    this.clientVat = clientVat;
    return this;
  }

   /**
   * Get clientVat
   * @return clientVat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientVat() {
    return clientVat;
  }


  public void setClientVat(String clientVat) {
    this.clientVat = clientVat;
  }


  public PlatformInvoice clientAddress(String clientAddress) {
    
    this.clientAddress = clientAddress;
    return this;
  }

   /**
   * Get clientAddress
   * @return clientAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getClientAddress() {
    return clientAddress;
  }


  public void setClientAddress(String clientAddress) {
    this.clientAddress = clientAddress;
  }


  public PlatformInvoice entries(Map<String, List<PlatformInvoiceEntry>> entries) {
    
    this.entries = entries;
    return this;
  }

  public PlatformInvoice putEntriesItem(String key, List<PlatformInvoiceEntry> entriesItem) {
    if (this.entries == null) {
      this.entries = new HashMap<>();
    }
    this.entries.put(key, entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, List<PlatformInvoiceEntry>> getEntries() {
    return entries;
  }


  public void setEntries(Map<String, List<PlatformInvoiceEntry>> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformInvoice platformInvoice = (PlatformInvoice) o;
    return Objects.equals(this.token, platformInvoice.token) &&
        Objects.equals(this.id, platformInvoice.id) &&
        Objects.equals(this.number, platformInvoice.number) &&
        Objects.equals(this.startdate, platformInvoice.startdate) &&
        Objects.equals(this.enddate, platformInvoice.enddate) &&
        Objects.equals(this.issuedate, platformInvoice.issuedate) &&
        Objects.equals(this.clientName, platformInvoice.clientName) &&
        Objects.equals(this.clientVat, platformInvoice.clientVat) &&
        Objects.equals(this.clientAddress, platformInvoice.clientAddress) &&
        Objects.equals(this.entries, platformInvoice.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, id, number, startdate, enddate, issuedate, clientName, clientVat, clientAddress, entries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformInvoice {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    startdate: ").append(toIndentedString(startdate)).append("\n");
    sb.append("    enddate: ").append(toIndentedString(enddate)).append("\n");
    sb.append("    issuedate: ").append(toIndentedString(issuedate)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    clientVat: ").append(toIndentedString(clientVat)).append("\n");
    sb.append("    clientAddress: ").append(toIndentedString(clientAddress)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

