/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.model;

import com.brand4impact.client.model.PlatformInvoiceEntry;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlatformInvoice
 */
public class PlatformInvoiceTest {
    private final PlatformInvoice model = new PlatformInvoice();

    /**
     * Model tests for PlatformInvoice
     */
    @Test
    public void testPlatformInvoice() {
        // TODO: test PlatformInvoice
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'startdate'
     */
    @Test
    public void startdateTest() {
        // TODO: test startdate
    }

    /**
     * Test the property 'enddate'
     */
    @Test
    public void enddateTest() {
        // TODO: test enddate
    }

    /**
     * Test the property 'issuedate'
     */
    @Test
    public void issuedateTest() {
        // TODO: test issuedate
    }

    /**
     * Test the property 'clientName'
     */
    @Test
    public void clientNameTest() {
        // TODO: test clientName
    }

    /**
     * Test the property 'clientVat'
     */
    @Test
    public void clientVatTest() {
        // TODO: test clientVat
    }

    /**
     * Test the property 'clientAddress'
     */
    @Test
    public void clientAddressTest() {
        // TODO: test clientAddress
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

}
