/*
 * Total API Reference
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.brand4impact.client.model;

import com.brand4impact.client.model.PlatformCompanyAddress;
import com.brand4impact.client.model.PlatformCompanyLegal;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PlatformCompany
 */
public class PlatformCompanyTest {
    private final PlatformCompany model = new PlatformCompany();

    /**
     * Model tests for PlatformCompany
     */
    @Test
    public void testPlatformCompany() {
        // TODO: test PlatformCompany
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'vat'
     */
    @Test
    public void vatTest() {
        // TODO: test vat
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'legal'
     */
    @Test
    public void legalTest() {
        // TODO: test legal
    }

    /**
     * Test the property 'sectorToken'
     */
    @Test
    public void sectorTokenTest() {
        // TODO: test sectorToken
    }

    /**
     * Test the property 'topicsToken'
     */
    @Test
    public void topicsTokenTest() {
        // TODO: test topicsToken
    }

}
